### ISSUE TITLE
lsh, rsh, or, xor, and - wciskanie więcej niż 1 x dozwolone

### ISSUE THREAD

**Issue by czaroslaw107** [ephmoc/calculator#1]
jak się wciska w nieskończoność to dodają się kolejne wartości w mini wyświretlaczu, a jak skonczy się wiersz to rozszerza się okno kalkulatora

**Comment by czaroslaw107** [comment]
![image](https://user-images.githubusercontent.com/3832500/40575275-62d80574-60e2-11e8-8885-41a49df07acd.png)

**Comment by ephmoc** [comment]
fix w commicie a14c49ea801412947f6e4777ccc369162339be8d
