### ISSUE TITLE
klawiatura BIN - wartości same się zmieniają i pojawia się zero samo

### ISSUE THREAD

**Issue by czaroslaw107** [ephmoc/calculator#2]
włączę 1 na pozycji np 62 pokazuje się wartość HEX 4000 0000 0000 0000 (prawidłowo)
włączę 1 na pozycji 63 pokazuje się wartość HEX C000 0000 0000 0000 (prawidłowo)
włączę 0 na pozycji 63 pojazje wszędzie 0 (a powinien 4000 0000 0000 0000)
pętla
włączę 1 ponownie na 63 - pokazuje hex 8000 0000 0000 0000 
włączę 0 na pozycji 63 pojazje wszędzie 0 itd..
koniec pętli

po tym fakcie jeśli włączę 0 na 63 i 0 na 62 to cała klawiatura zwęża się
![image](https://user-images.githubusercontent.com/3832500/40575366-0e332858-60e4-11e8-8d44-38d6d3265c5b.png)

**Comment by ephmoc** [comment]
Problem zapewne w coordynatach zczytywanych z przycisku - zajme sie tym

**Comment by czaroslaw107** [comment]
Sytuacja jest taka sama dla każdego słowa (qword, dword itd.) - czyli zawsze taka sama sytuacja z ostatnim znakiem (63 dla qword, 31 dla dword ) itd

**Comment by ephmoc** [comment]
mozliwe ze proble jest w konwersji bitu znaku

**Comment by ephmoc** [comment]
Tak, problem byl w konwersji bitu znaku.

**Comment by ephmoc** [comment]
Fix: d5ed6e8fc451e1077500d8b8efc42e89bc5548b8
