### ISSUE TITLE
Pamięć - MS ucina znaki

### ISSUE THREAD

**Issue by czaroslaw107** [ephmoc/calculator#3]
![image](https://user-images.githubusercontent.com/3832500/40575417-ff4f2552-60e4-11e8-9340-8cd986d3a3ca.png)

**Comment by ephmoc** [comment]
jakie znaki???

**Comment by czaroslaw107** [comment]
mc, m+, m- w zapamiętanych pozycjach

**Comment by ephmoc** [comment]
Done
